### ISSUE TITLE
BatMass for Mac

### ISSUE THREAD

**Issue by rsalek** [chhh/batmass#1]
Hello Dmitry, 
I installed the .dmg for MAC and followed your installer, but does not seem to open up?
My System OSX version 10.11.4 with 8 GB memory. 
Java version j"1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode).

The older version was working fine/any suggestion?
BW,
Reza
P.S Nice work BTW

**Comment by chhh** [comment]
Thanks! I'll  look into it next week as I don't have access to OSX crigh now. Must be something stupid I did when trimming it up the last time. In the meantime all the older installers are still available in the releases section: https://github.com/chhh/batmass/releases

**Comment by chhh** [comment]
@rsalek Finally, the issue has been identified. 
The startup shell script script `/Applications/batmass.app/Contents/Resources/batmass/bin/batmass` is not executable after installation on OSX.  
Running `chmod +x` on it fixes the problem.   
I'll repackage the installer.

**Comment by rsalek** [comment]
Thank you worked.
