### ISSUE TITLE
writing mgf or mzXML /mzML files

### ISSUE THREAD

**Issue by gsaxena888** [chhh/batmass#11]
Is it possible to use BatMass to *create* mgf, mzXML, or mzML files? (I know we can read mzXML files.) If it is possible, do you have some test code or example code that we could follow? If it's not supported in the library, do you have any suggestions for libraries that do support writing mgf, mzXML, or mzML files in Java?

**Comment by chhh** [comment]
I didn't write any real "writers", you can take a look at the example for pepxml [here](https://github.com/chhh/MSFTBX/blob/master/MSFileToolbox/src/umich/ms/fileio/filetypes/pepxml/example/PepXmlWriteExample.java), it will go the same way for writing mzxml. mzML is more involved as you need to know controlled vocabulary (cv) terms for everything that you write out. That mapping of cv terms is very cumbersome.  
Writing mgf should not be a problem to do yourself. If you want a library for that, you can look at [MSDK](https://github.com/msdk/msdk), might look a little overwhelming for you though. Here's a link to mgf export test in msdk: https://github.com/msdk/msdk/blob/master/msdk-io-mgf/src/test/java/io/github/msdk/io/mgf/MgfFileExportMethodTest.java
