### ISSUE TITLE
Clean build of BatMass fails with three errors 

### ISSUE THREAD

**Issue by etrh** [chhh/batmass#14]
I want to read CEF files using BatMass and as I understand, this functionality is not provided by default in BatMass. So I am going through [this](http://batmass.org/tutorial/setting-up-development-environment/) tutorial in order to be able to add the `umich.ms.batmass.filesupport.files.types.agilent.cef.data` module to BatMass in [this way](http://batmass.org/tutorial/developing-first-plugin/).

While going through [this](http://batmass.org/tutorial/setting-up-development-environment/) tutorial, I get stuck in the very last step, i.e. clean build BatMass. Clean build of MSFTBX, BatMassLibs, and BatMassExternalSuite are all successful, but when I try to `Clean and Build` BatMass, I get 3 errors:

> Desktop\batmass-projects\batmass-master\FileSupport\src\umich\ms\batmass\filesupport\files\types\mzml\MzMLLCMSDataProvider.java:42: error: cannot access AbstractFile
>         LCMSData lcmsData = new LCMSData(lcmsDataSource, scans);
>   class file for umich.ms.util.file.AbstractFile not found
> 
> Desktop\batmass-projects\batmass-master\FileSupport\src\umich\ms\batmass\filesupport\files\types\pepxml\data\PepxmlFeature.java:53: error: incompatible types: possible lossy conversion from double to float
>         float dm = Math.abs(sh.getMassdiff());
> 
> Desktop\batmass-projects\batmass-master\FileSupport\src\umich\ms\batmass\filesupport\files\types\pepxml\providers\PepxmlFeaturesDataSource.java:54: error: incompatible types: Double cannot be converted to Float
>             Float rt = sum.getSpectrumQuery().get(0).getRetentionTimeSec();

Windows 10
NetBeans IDE 8.2
Java Version 8 Update 172 (build 1.8.0_172-b11)
jdk1.8.0_172
jre1.8.0_172

**Comment by chhh** [comment]
@etrh Sorry, was away, didn't see your post.

Are you looking for a library to read CEF files? Or you want to visualize them with batmass? By default IIRC you can right click the "Features" folder in the project explorer and it should be able to pull in CEF files.

Those errors crop up because of recent updates to MSFTBX, I'll fix the build.

**Comment by chhh** [comment]
Not yet, I've only dealt with CEF files once several years ago and thats when I wrote support for it. Would you mind sharing a sample file that doesn't want to open for you, then I can quickly debug and fix.

**Comment by etrh** [comment]
Thanks for devoting your time to this. I just sent you two CEF files by email.

**Comment by chhh** [comment]
Thanks, I'm finally back home from ASMS, so will take a look

**Comment by chhh** [comment]
Ok, I think I know what the problem is - your CEF files don't have "RTRanges" tags for compounds. When the original version was written I've only seen files with those tags, so I thought they were mandatory. I'll try to update it to use a single RT value for the whole compound.

**Comment by chhh** [comment]
@etrh Ok, everything has been updated, you can start batmass and you'll get the prompt to auto-update several modules. CEF support is most likely not exactly what you're expecting, but it works and navigation when the list of features is synced to 2d view also works.
