### ISSUE TITLE
Batmass does not install on Ubuntu 24.04

### ISSUE THREAD

**Issue by tekitch** [chhh/batmass#23]
Hi Dmitry, 

Setting up batmass on a new system I'm unable to get batmass-linux.sh to complete. It errors out as below. I assume that it needs a specific Java as per the run issues but I'm not sure where to edit the .sh to point to the Adoptium Java build. 

![image](https://github.com/user-attachments/assets/573d6053-2882-4f69-98bf-37ef37ab27de)

**Comment by chhh** [comment]
Hey @tekitch , looks like you were able to resolve that yourself. If you don't mind, please share with the rest of us how was that solved?

Did you have to downgrade to an older Java version? Pack200 was some sort of compression mechanism in java builds and it was removed from standard java distributions at some point.

One thing to note is that you don't really need the installer. It's ok to grab the zip file, unpack it anywhere on your system, edit the config file to point to an old JRE/JVM and launch batmass using one of the launch methods in /bin folder.
