### ISSUE TITLE
Problem using digits

### ISSUE THREAD

**Issue by Mystilivia** [chhh/batmass#3]
Hello, 
Great job on this tool !
I encounter a problem when I try to search for precise mass using digits, in the example windows it shows 'coma', and when I enter the separator, I can only use period, which returns an error (see below).

![go to](https://cloud.githubusercontent.com/assets/17728771/24108103/f3930ad2-0d8c-11e7-9776-d1e5954dc369.jpg)

Returned error :
![information](https://cloud.githubusercontent.com/assets/17728771/24108122/fead2024-0d8c-11e7-8c3c-7dbbdbb76779.jpg)

Same with XIC :
![image](https://cloud.githubusercontent.com/assets/17728771/24108341/9f29179c-0d8d-11e7-9822-81bae6e72787.png)

which return full tic without subsetting anything.
I tried to change the system language settings to use period instead of coma, but it doesn't work.

**Comment by chhh** [comment]
Hi, this is definitely related to system locale settings, I'll fix that!

**Comment by chhh** [comment]
@Mystilivia By the looks of screenshots you're on Win7. What are your system regional settings? I can't seem to force it to use commas even when I set it as a decimal separator in the system settings.
Can you please start BatMass and go to **View -> IDE Log** and post the contents here? It has the information about the locale.

I've pushed an update that allows input of commas into those text fields and changed how they are parsed. Just restart BatMass, you should get a notification about available updates. You'll get a warning that the updates are not signed, that's ok, they are always that way. If that won't be enough, I'll need to investigate further.

**Comment by Mystilivia** [comment]
@chhh My system is on Win7 in French : 
![image](https://cloud.githubusercontent.com/assets/17728771/24213654/7c9295bc-0f33-11e7-995e-e4a8bc9a60cb.png)

On my side too, changing system default settings to use periods doesn't affect the software.

Thanks for the update, now when I open the 'Go To' tools, it shows a comma by default in the input box, and when I enter value, forcing comma, it works !
![image](https://cloud.githubusercontent.com/assets/17728771/24213768/e1e40216-0f33-11e7-9b3f-3524baf733de.png)

Idem for XIC, it works well.

The only drawback is when using the digits key on the numeric pad. It uses the period by default, which is not recognised by the soft on my system. It seems that maybe Batmass uses system regional settings for display, but doesn't use them for input ?

**Comment by chhh** [comment]
@Mystilivia Have you tried using dots in the input? Theoretically I've just changed the text fields to allow dots and commas, and before parsing the numbers, it replaces all occurrences with just a single dot and then parses. So it should work. But as I said, I wasn't able to confirm that so far.

When you type on the numpad does it print the dots? If it prints, what happens after you press OK?

**Comment by Mystilivia** [comment]
@chhh You are right, using dots actually works :
![image](https://cloud.githubusercontent.com/assets/17728771/24217401/fd16b090-0f3f-11e7-9f33-f7dfc3d51c4a.png)

resulting in :
![image](https://cloud.githubusercontent.com/assets/17728771/24217422/0b5f77a4-0f40-11e7-8435-7347e14fdfab.png)

Thanks for solving this issue !

**Comment by chhh** [comment]
You're welcome!
