### ISSUE TITLE
Batmass not lunching on Mac Sierra OS 10.12.5

### ISSUE THREAD

**Issue by rsalek** [chhh/batmass#5]
Hello Dmitry,

Hope all is well, I download the latest version and successfully installed it on my machine, however it, does not lunch "The application "batmass" can't be opened". Any suggestion? 

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

Reza

**Comment by rsalek** [comment]
Ah, seems same old problem: The startup shell script script /Applications/batmass.app/Contents/Resources/batmass/bin/batmass is not executable after installation on OSX.
Running chmod +x fixed the problem.

**Comment by chhh** [comment]
Thanks Reza, I'll check out the installer again when I have time! ASMS is coming, need to prepare
