### ISSUE TITLE
JVM creation failed

### ISSUE THREAD

**Issue by Alemarcohen** [chhh/batmass#7]
I just downloaded Batmass on my Window7 computer, and when I run it I get the following error:

JVM creation failed

Any ideas?
Thanks
Alex

**Comment by chhh** [comment]
Hi Alex,
Most likely you don't have enough RAM for the default configuration. By default the JVM starts with "-Xmx4G" parameter, which requires the system to have at least 4GB of **available** memory.

If that is the problem, you can lower the memory requirement in the config file ([see here](https://github.com/chhh/batmass#important-before-you-begin) - open `<install_path>/etc/batmass.conf`, find `default_options` string there and change `-J-Xmx4G` to something lower, e.g. `-J-Xmx2G`)

Could you also please run in **cmd.exe** `java -version` command and post results here?

**Comment by Alemarcohen** [comment]
Dmitry

I had already fixed the problem. I had installed batmass in an additional hard drive (/:e not c:) and batmatfave me that error. I reinstalled in c: and reconfigured the path to JRE... Working sweet now, THANKS!!!

Alex

**Comment by chhh** [comment]
@Alemarcohen 
Installation path was likely not the problem, but JRE config can definitely be screwed sometimes for no apparent reason. 
I'm hoping to update BatMass in the next 6 months, so don't uninstall, run it from time to time and you'll get automatic notifications about the updates! :)

If you have any particular needs/ideas to be implemented, don't hesitate to leave them here in the bug tracker!

**Comment by Alemarcohen** [comment]
Can the spectra be linked yo the TIC instead of the 2D map?? Couldn't figure that out! 
Best!
Alex

**Comment by chhh** [comment]
Yes, but that's not really functional. The spectrum and chromatogram viewers need to be rewritten completely, then all will work as you expect. That's on the list for improvements.

**Comment by Titan100** [comment]
@chhh 
I have a same issue "JVM Failed". I tried to change `-J-Xmx4G` to `-J-Xmx2G` as you suggested and ran as administrator to save the change but still the same error pops up.
I have herewith attached `java -version` screenshot.

![2018-08-06 10_25_35-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/16618391/43722520-7101a8e4-9963-11e8-976c-2aa851f6183f.png)

**Comment by chhh** [comment]
@Titan100 
In some cases it can't find a java installation and I don't know why. However, there's a way to tell BatMass exactly where to look for java. In the same `batmass.conf` file, uncomment the line that starts with `#jdkhome=...`, i.e. change it to `jdkhome=...` and use the path to your java installation, e.g. `"C:\Programs\Java\zulu-jdk-8"`.
You don't necessarily need the who JDK (which is the Java Development Kit), you technically need only the JRE (Java Runtime Environment), but the current way Oracle started distributing their JRE is a little tricky as it copies parts of the JRE on Windows to <win>/System32 directory, for example. So the simplest in your case would be to install a JDK (either [from Oracle](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), or a pre-built [OpenJDK](https://cdn.azul.com/zulu/bin/zulu8.30.0.1-jdk8.0.172-win_x64.msi) (Java 8 x64) which I would recommend) and use the installation path for `jdkhome=...`.

**Comment by Titan100** [comment]
@chhh 
Hi, I set the java path and ran the batmass and showed the attached issue below. I cannot visualize the chromatogram and other, instead it shows me as attached below. Right click on LC-MS (.mzXML) file did not show "view option" instead showed be the source codes. Please refer to the attachments 

![issue_2018-08-06 17_38_42-batmass](https://user-images.githubusercontent.com/16618391/43742633-a633370c-99a0-11e8-9d19-23ca96879094.png)
![issue2_2018-08-06 17_41_12-batmass](https://user-images.githubusercontent.com/16618391/43742639-aaef05dc-99a0-11e8-95dd-bd9d15ac1047.png)

**Comment by chhh** [comment]
Interesting, this is definitely not what's supposed to happen. I see that it didn't recognize the mzXML file at all, it doesn't have an icon etc.

Can you please try downloading just the zip file distribution of batmass (i.e. without the installer), [here's the link](https://github.com/chhh/batmass/releases/download/v0.3.1/batmass.zip).
Unzip it, then run `<unzipped-path>/bin/batmass64.exe`. If it doesn't find java, edit the config file as before. Upon the first run you should get a notification balloon in the bottom right corner that updates are available, click it and install the updates. I just tried it and it worked for me.

**Comment by Titan100** [comment]
Hi @chhh 
Still same issue. It did not recognize .mzXML file. Downloaded zip file, unzipped, and ran batmass64.exe.
 Here is the screenshot.
![image](https://user-images.githubusercontent.com/16618391/43780617-037cfcd0-9a29-11e8-93b6-8f48d6840e1c.png)

![image](https://user-images.githubusercontent.com/16618391/43780671-19dac84a-9a29-11e8-8ed0-020001cc1c38.png)
![image](https://user-images.githubusercontent.com/16618391/43780688-280fd0ea-9a29-11e8-9c55-86f943582f04.png)

**Comment by chhh** [comment]
Ok, super strange, I can't reproduce.
Go to main menu `Help -> About` and please post the content here.

You'll see something like
```
Product Version: BatMass 201510222201
Java: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01
Runtime: Java(TM) SE Runtime Environment 1.8.0_144-b01
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (batmass)
User directory: C:\Users\chhh\AppData\Roaming\.batmass\dev
Cache directory: C:\Users\chhh\AppData\Roaming\.batmass\dev\var\cache
```
Quit batmass and manually delete your equivalent of `C:\Users\chhh\AppData\Roaming\.batmass` directory.
Can you try it in a virtual machine? I just installed a new Ubuntu into VMWare Player, downloaded the zip distro of batmass, ran `./<batmass>/bin/batmass` and this worked.
